"""return_to_work delete id

Revision ID: 119316391576
Revises: 25ec37511813
Create Date: 2025-06-09 02:55:56.929800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '119316391576'
down_revision: Union[str, None] = '25ec37511813'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_return_to_work_id'), table_name='return_to_work')
    op.drop_column('return_to_work', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('return_to_work', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.create_index(op.f('ix_return_to_work_id'), 'return_to_work', ['id'], unique=False)
    # ### end Alembic commands ###
