"""add return_to_work table

Revision ID: 25ec37511813
Revises: 000000000000
Create Date: 2025-06-09 01:29:20.005682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25ec37511813'
down_revision: Union[str, None] = '000000000000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('return_to_work',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('queue', sa.String(), nullable=False),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('summary', sa.String(), nullable=False),
    sa.Column('assignee', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('returns_to_work', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_return_to_work_id'), 'return_to_work', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_return_to_work_id'), table_name='return_to_work')
    op.drop_table('return_to_work')
    # ### end Alembic commands ###
